### ISSUE TITLE
Check imports

### ISSUE THREAD

**Issue by cloetensbrecht** [codeurs/secrets-replace#3]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: rlespinasse/github-slug-action@v3.x, codeurs/secrets-replace@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by DimitriCodeurs** [comment]
Fixed in v3
